require 'epages/category'
require 'epages/content_page_summary'
require 'epages/custom_attribute'
require 'epages/error'
require 'epages/image'
require 'epages/image_size'
require 'epages/legal' # posible refactor to the name
require 'epages/link'
require 'epages/price'
require 'epages/price_info'
require 'epages/product'
require 'epages/shop'
require 'epages/utils'
require 'epages/variation'
require 'epages/variation_attribute'
require 'epages/version'

require 'epages/rest/api'
require 'epages/rest/carts'
require 'epages/rest/categories'
require 'epages/rest/legal'
require 'epages/rest/products'
require 'epages/rest/request'
require 'epages/rest/shipping_methods'
require 'epages/rest/shop'
require 'epages/rest/utils'
